- name: Load DB values from .env (development)
  when: not use_ssm
  include_vars:
    file: "{{ env_file }}"
    name: db_env

- name: Set DB variables from env
  when: not use_ssm
  set_fact:
    db_name: "{{ db_env.WORDPRESS_DB_NAME }}"
    db_user: "{{ db_env.WORDPRESS_DB_USER }}"
    db_password: "{{ db_env.WORDPRESS_DB_PASSWORD }}"
    db_host: "{{ db_env.WORDPRESS_DB_HOST }}"
    db_port: "{{ db_env.WORDPRESS_DB_PORT | default('3306') }}"
    db_charset: "{{ db_env.WORDPRESS_DB_CHARSET | default('utf8mb4') }}"

- name: Load DB values from AWS SSM
  when: use_ssm
  set_fact:
    db_name: "{{ lookup('aws_ssm', db_ssm_parameters.name, region=aws_region) }}"
    db_user: "{{ lookup('aws_ssm', db_ssm_parameters.user, region=aws_region) }}"
    db_password: "{{ lookup('aws_ssm', db_ssm_parameters.password, region=aws_region) }}"
    db_host: "{{ lookup('aws_ssm', db_ssm_parameters.host, region=aws_region) }}"
    db_port: "{{ lookup('aws_ssm', db_ssm_parameters.port, region=aws_region) }}"
    db_charset: "{{ lookup('aws_ssm', db_ssm_parameters.charset, region=aws_region) }}"
