version: '3'
services:
  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: .
      dockerfile: ./infrastructure/docker/wordpress/Dockerfile
    ports:
      - '8088:80'
    volumes:
      - ./wordpress:/var/www/html
      - ./infrastructure/:/workspace/