AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SystemName:
    Type: String
    Description: System Name
  SystemDomain: 
    Type: String
    Description: System Domain Name
  SystemEnv:
    Type: String
    Description: Environment type
    Default: staging
    AllowedValues:
      - "production"
      - "staging"
      - "test"
      - "development"
Resources:
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ${SystemName}-${SystemEnv}
      Description: !Sub ${SystemName} ${SystemEnv} group
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          TagFilters:
            - Key: "System"
              Values: 
              - !Ref SystemName
            - Key: "Env"
              Values: 
              - !Ref SystemEnv
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${SystemName}-${SystemEnv}-tfstate
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Env"
          Value: !Ref SystemEnv
        - Key: "System"
          Value: !Ref SystemName
        - Key: Name
          Value: !Sub ${SystemName}-${SystemEnv}-tfstate
        - Key: "Description"
          Value: "tf-state-bucket"
  DynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${SystemName}-${SystemEnv}-table
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
  Repository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub ${SystemName}-${SystemEnv}-main-repo
      EncryptionConfiguration:
        EncryptionType: "AES256"
      Tags:
        - Key: "Env"
          Value: !Ref SystemEnv
        - Key: "System"
          Value: !Ref SystemName
  # SSM パラメータ
  # 
  # !!! KMSでキー生成し、暗号化すること（Secure String へ）
  DBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/db_password
      Type: String
      Value: "DummyDatabasePassword"
      Description: Database password
      Tags: 
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  DBUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/db_user
      Type: String
      Value: "DummyDatabaseUser" 
      Description: Database user
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  DBName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/db_name
      Type: String
      Value: "DummyDatabaseName" 
      Description: Database Name
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  DBPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/db_port
      Type: String
      Value: "DummyDatabasePort"
      Description: Database port
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  DBHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/db_host
      Type: String
      Value: "DummyDatabaseHost"
      Description: Database Host
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  isProductionOperation:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/isProductionOperation
      Type: String
      Value: "0"
      Description: is Production Operation
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
  ecrRepoURL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${SystemEnv}/ecrRepoURL
      Type: String
      Value: "0"
      Description: ECR Repo URL
      Tags:
        "Env": !Ref SystemEnv
        "System": !Ref SystemName
