- hosts: localhost
  vars:
      env: production
  become: true
  vars_files:
    - group_vars/prouction.yml
  roles:
    - role: common
      tasks_from: load_db_vars
    - php
    - apache
    - mysql
    - wordpress

