- name: Download latest WordPress for each virtualhost
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "/tmp/wordpress_{{ item.servername }}.tar.gz"
    mode: '0644'
  loop: "{{ virtualhosts }}"

- name: Ensure document root exists
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'
  loop: "{{ virtualhosts }}"

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress_{{ item.servername }}.tar.gz"
    dest: "{{ item.document_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ item.document_root }}/wp-config-sample.php"
  loop: "{{ virtualhosts }}"

- name: Deploy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ item.document_root }}/wp-config.php"
    owner: apache
    group: apache
    mode: '0644'
  loop: "{{ virtualhosts }}"

- name: Set directory permissions
  shell: find "{{ item.document_root }}" -type d -exec chmod 755 {} \;
  loop: "{{ virtualhosts }}"

- name: Set file permissions
  shell: find "{{ item.document_root }}" -type f -exec chmod 644 {} \;
  loop: "{{ virtualhosts }}"
