use_ssm: true

db_ssm_parameters:
  name:     /staging/wordpress/db/name
  user:     /staging/wordpress/db/user
  password: /staging/wordpress/db/password
  host:     /staging/wordpress/db/host
  port:     /staging/wordpress/db/port
  charset:  /staging/wordpress/db/charset

aws_region: ap-northeast-1

server_name: staging.example.com
document_root: /var/www/html/wordpress

# Virtualhosts
virtualhosts:
  - servername: staging.example.com
    document_root: /var/www/html/wordpress
    fpm_pool: wordpress
  # バーチャルホストでサーバを追加したい場合は下記のように追加
  # - servername: example2.com
  #   document_root: /var/www/example2
  #   fpm_pool: example2

# PHP
php_max_execution_time: 60
php_max_input_time: 90
php_memory_limit: "256M"
php_post_max_size: "16M"
php_upload_max_filesize: "8M"
php_timezone: "Asia/Tokyo"