---
- name: Restart PHP-FPM
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted
  when: use_systemd | default(true)

- name: Restart PHP-FPM (non-systemd)
  shell: |
    pkill php-fpm || true
    php-fpm -D
  when: not use_systemd | default(false)
